### PR TITLE
Update links for buttons that lead to dashboard.

### PR DESCRIPTION
**Pull request by tvweinstock**
**Problem:**
- The link to the dashboard for demoing analytics is broken

**Solution:**
- Link for analytics has been hard-coded to the `atis-prods` index where the analytics v2 is being populated by [fake analytics](https://github.com/algolia/atis-analytics-faker)
- A second button has been added and assigned the correct link for the logged in user's index. The pid had been hard coded to go to the correct application.

### CODE REVIEW

**Comment by ehayman** [comment]
Yay! Thanks Tobi!

**Comment by ehayman** [comment]
@tvweinstock can you go ahead and merge this into develop, then make a PR to merge develop into master? I'll approve and deploy then.

**Comment by tvweinstock** [comment]
@ehayman this has already been merged to develop this PR is for merging develop into master

**Comment by ehayman** [comment]
d'oh 💃

**Pull request merged**
